UPDATE config SET config_value='2.20' WHERE config_name='version';

ALTER TABLE mrtg DROP COLUMN interface_ip;
ALTER TABLE mrtg DROP COLUMN interface_name;
ALTER TABLE mrtg DROP COLUMN iftype;
ALTER TABLE mrtg DROP COLUMN title_ip;
ALTER TABLE mrtg DROP COLUMN pagefoot;
ALTER TABLE mrtg DROP COLUMN addhead;
ALTER TABLE mrtg DROP COLUMN bodytag;
ALTER TABLE mrtg DROP COLUMN extension;
ALTER TABLE mrtg DROP COLUMN directory;
ALTER TABLE mrtg DROP COLUMN pngtitle;
ALTER TABLE mrtg DROP COLUMN background;

ALTER TABLE mrtg ADD COLUMN kilo varchar(255);
ALTER TABLE mrtg ADD COLUMN rrdrowcount30m varchar(255);
ALTER TABLE mrtg ADD COLUMN rrdrowcount2h varchar(255);
ALTER TABLE mrtg ADD COLUMN rrdrowcount1d varchar(255);
ALTER TABLE mrtg ADD COLUMN rrdhwrras varchar(255);
ALTER TABLE mrtg ADD COLUMN sfilename varchar(255);
ALTER TABLE mrtg ADD COLUMN setenv varchar(255);
ALTER TABLE mrtg ADD COLUMN pagetop varchar(255);

ALTER TABLE mrtg ALTER COLUMN filename TYPE varchar(255);
ALTER TABLE mrtg ALTER COLUMN maxbytes TYPE varchar(255);
ALTER TABLE mrtg ALTER COLUMN target TYPE varchar(255);
ALTER TABLE mrtg ALTER COLUMN xsize TYPE varchar(255);
ALTER TABLE mrtg ALTER COLUMN ysize TYPE varchar(255);
ALTER TABLE mrtg ALTER COLUMN xzoom TYPE varchar(255);
ALTER TABLE mrtg ALTER COLUMN yzoom TYPE varchar(255);
ALTER TABLE mrtg ALTER COLUMN xscale TYPE varchar(255);
ALTER TABLE mrtg ALTER COLUMN yscale TYPE varchar(255);
ALTER TABLE mrtg ALTER COLUMN ytics TYPE varchar(255);
ALTER TABLE mrtg ALTER COLUMN yticsfactor TYPE varchar(255);
ALTER TABLE mrtg ALTER COLUMN factor TYPE varchar(255);
ALTER TABLE mrtg ALTER COLUMN step TYPE varchar(255);
ALTER TABLE mrtg ALTER COLUMN weekformat TYPE varchar(255);
ALTER TABLE mrtg ALTER COLUMN rrdrowcount TYPE varchar(255);
ALTER TABLE mrtg ALTER COLUMN timestrpos TYPE varchar(255);
ALTER TABLE mrtg ALTER COLUMN unscaled TYPE varchar(4);
ALTER TABLE mrtg ALTER COLUMN withpeak TYPE varchar(4);
ALTER TABLE mrtg ALTER COLUMN suppress TYPE char(1);
ALTER TABLE mrtg ALTER COLUMN routeruptime TYPE varchar(255);
ALTER TABLE mrtg ALTER COLUMN routername TYPE varchar(255);
ALTER TABLE mrtg ALTER COLUMN ipv4only TYPE varchar(255);
ALTER TABLE mrtg ALTER COLUMN absmax TYPE varchar(255);
ALTER TABLE mrtg ALTER COLUMN options TYPE varchar(255);
ALTER TABLE mrtg ALTER COLUMN kmg TYPE varchar(255);
ALTER TABLE mrtg ALTER COLUMN colours TYPE varchar(255);
ALTER TABLE mrtg ALTER COLUMN ylegend TYPE varchar(255);
ALTER TABLE mrtg ALTER COLUMN shortlegend TYPE varchar(255);
ALTER TABLE mrtg ALTER COLUMN legend1 TYPE varchar(255);
ALTER TABLE mrtg ALTER COLUMN legend2 TYPE varchar(255);
ALTER TABLE mrtg ALTER COLUMN legend3 TYPE varchar(255);
ALTER TABLE mrtg ALTER COLUMN legend4 TYPE varchar(255);
ALTER TABLE mrtg ALTER COLUMN legendi TYPE varchar(255);
ALTER TABLE mrtg ALTER COLUMN legendo TYPE varchar(255);
ALTER TABLE mrtg ALTER COLUMN timezone TYPE varchar(255);
ALTER TABLE mrtg ALTER COLUMN timestrfmt TYPE varchar(255);

ALTER TABLE mrtg ADD PRIMARY KEY (id);
ALTER TABLE templates ADD PRIMARY KEY (id);
ALTER TABLE global ADD PRIMARY KEY (workdir);
ALTER TABLE global_err ADD PRIMARY KEY (workdir);
